name: 'Upstream Tag Sync'
description: 'Creates a PR when new tags are detected in an upstream repository, allowing controlled synchronization with upstream releases'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  target-repo:
    description: 'Repository to sync (format: owner/repo)'
    required: true
  upstream-repo:
    description: 'Upstream repository to sync from (format: owner/repo)'
    required: true
  github-token:
    description: 'Classic token from a service account with "repo" scope. IMPORTANT: Do not use GITHUB_TOKEN or fine-grained tokens, as GITHUB_TOKEN cannot trigger workflows and fine-grained tokens require per-repo access configuration. See README.md for service account setup.'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.mjs'
