name: "Upstream Tag Sync"
description: "Creates a PR when new tags are detected in the upstream repository"
branding:
  icon: "git-pull-request"
  color: "blue"
inputs:
  target-repo:
    description: "Repository to sync (format: owner/repo)"
    required: true
  upstream-repo:
    description: "Upstream repository to sync from"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
