name: Linting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['upstream-tag-on-merge', 'upstream-tag-sync']

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: v1.2.19

      - name: Install Dependencies
        run: bun install --frozen-lockfile
        working-directory: ./${{ matrix.project }}

      - name: Run linter
        run: bun run lint
        working-directory: ./${{ matrix.project }}
